apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: tiltak-tilsagnsbrev
  namespace: default
  labels:
    team: teamtag
spec:
  image: navikt/tiltak-tilsagnsbrev:{{version}}
  team: teamtag
  port: 8080
  replicas:
    min: 1
    max: 1
  liveness:
    path: /tiltak-tilsagnsbrev/internal/healthcheck
    initialDelay: 30
    timeout: 1
  readiness:
    path: /tiltak-tilsagnsbrev/internal/healthcheck
    initialDelay: 30
    timeout: 1
  ingresses:
    - {{ingress}}
  vault:
    enabled: true
    paths:
        #test
      - kvPath: "serviceuser/data/test/srvtiltak-tilsagns"
      #preprod
     # - kvPath: "serviceuser/data/dev/srvtiltak-tilsagns"
        mountPath: "/secrets/serviceuser/srvtiltak-tilsagns/"

        #preprod
      - kvPath: "kv/preprod/fss/tiltak-tilsagnsbrev/default"
        mountPath: "/var/run/secrets/nais.io/vault/"

  # production:
#      - kvPath: "serviceuser/data/prod/srvtiltak-tilsagns"
#        mountPath: "/secrets/serviceuser/srvtiltak-tilsagns/"

  env:
  - name: SPRING_PROFILES_ACTIVE
    value: {{spring-profil}}
  webproxy: true
  prometheus:
    enabled: false
    path: /tiltak-tilsagnsbrev/internal/actuator/prometheus

