apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: tiltak-tilsagnsbrev
  namespace: default
  labels:
    team: teamtag
spec:
  image: navikt/tiltak-tilsagnsbrev:{{version}}
  team: teamtag
  port: 8080
  replicas:
    min: 1
    max: 1
  resources:
    limits:
      cpu: 2000m
      memory: 3000Mi
    requests:
      cpu: 500m
      memory: 600Mi
  liveness:
    path: /tiltak-tilsagnsbrev/internal/healthcheck
  readiness:
    path: /tiltak-tilsagnsbrev/internal/healthcheck
  vault:
    enabled: true
    paths:
      - kvPath: "serviceuser/data/dev/srvtiltak-tilsagns"
        mountPath: "/secrets/serviceuser/srvtiltak-tilsagns/"
# production:
#      - kvPath: "serviceuser/data/prod/srvtiltak-tilsagns"
#        mountPath: "/secrets/serviceuser/srvtiltak-tilsagns/"

  env:
  - name: SPRING_PROFILES_ACTIVE
    value: {{spring-profil}}
  webproxy: true
  prometheus:
    enabled: false
