logging:
  level:
    no.nav.tag.tilsagnsbrev: INFO
    org.springframework.kafka.listener.LoggingErrorHandler: OFF

spring:
  kafka:
    bootstrap-servers: a01apvl00145.adeo.no:8443, a01apvl00146.adeo.no:8443, a01apvl00147.adeo.no:8443, a01apvl00148.adeo.no:8443, a01apvl00149.adeo.no:8443, a01apvl00150.adeo.no:8443
    client-id: tiltak-tilsagnsbrev
    properties:
      security.protocol: SASL_SSL
      sasl:
        mechanism: PLAIN
        jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username="${tilsagnsbrev_srvuser}" password="${tilsagnsbrev_srvpwd}";
      ssl.truststore:
        location: ${javax.net.ssl.trustStore}
        password: ${javax.net.ssl.trustStorePassword}
    consumer:
      group-id: ${tilsagnsbrev.consumer.group.id}

tilsagnsbrev:
  retry:
    cron: ${tilsagnsbrev.process.cron}
  database:
    database-navn: tiltak-tilsagnsbrev-prod
    database-url: ${spring.datasource.url}
    vault-sti: postgresql/prod-fss
    minimum-idle: 1
    maximum-pool-size: 1
    max-lifetime: 300000
  integrasjon:
    pdfgen:
      uri: ${tilsagnsbrev.pdfgen.url}
    joark:
      uri: ${tilsagnsbrev.joark.url}
    sts:
      uri: ${tilsagnsbrev.sts.url}
      ws-uri: ${tilsagnsbrev.sts.ws.url}
      bruker: ${tilsagnsbrev_srvuser}
      passord: ${tilsagnsbrev_srvpwd}
    altinn:
      uri: ${altinn.correspondence.url}
      systemBruker: ${tilsagnsbrev_altinn_system_bruker}
      systemPassord: ${tilsagnsbrev_altinn_system_passord}