server:
  port: 8082

spring:
  kafka:
    consumer:
      bootstrap-servers: ${spring.embedded.kafka.brokers}

  main:
    banner-mode: "console"

tilsagnsbrev:
  integrasjon:
    pdfgen:
      uri: http://localhost:8090
    joark:
      uri: http://localhost:8090
    sts:
      uri: http://localhost:8090
      ws-uri: http://localhost:8090
      bruker: ${tilsagnsbrev_srvuser}
      passord: ${tilsagnsbrev_srvpwd}
    altinn:
      uri: http://localhost:8090/ekstern/altinn/BehandleAltinnMelding/v1
      systemBruker: systemBruker
      systemPassord: systemPassord