server:
  port: 8082

spring:
  kafka:
    consumer:
      bootstrap-servers: ${spring.embedded.kafka.brokers}

  main:
    banner-mode: "console"

tilsagnsbrev:
  integrasjon:
    pdfgen:
      uri: http://localhost:5913
    joark:
      uri: uri
    sts:
      uri: uri
      bruker: ${tilsagnsbrev_srvuser}
      passord: ${tilsagnsbrev_srvpwd}
    altinn:
      uri: http://localhost:8090
      user: ${tilsagnsbrev.mq.user}
      password: ${tilsagnsbrev.mq.pwd}