server:
  port: 8082

spring:
  kafka:
    consumer:
      bootstrap-servers: ${spring.embedded.kafka.brokers}
  datasource:
    platform: postgres
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
    username: sa
    password: sa
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console

  main:
    banner-mode: "console"

tilsagnsbrev:
  integrasjon:
    pdfgen:
      uri: http://localhost:5913
    altinn:
      queue: DEV.QUEUE.1
    joark:
      uri: uri
    sts:
      uri: uri
      bruker: bruker
      passord: passord

ibm:
  mq:
    queueManager: QM1
    channel: DEV.ADMIN.SVRCONN
    connName: localhost(32794)
    user: ${tilsagnsbrev_srvuser}
    password: ${tilsagnsbrev_srvpwd}