
spring:
  kafka:
    bootstrap-servers: d26apvl00159.test.local:8443,d26apvl00160.test.local:8443,d26apvl00161.test.local:8443
    consumer:
      ssl:
        protocol: SASL_SSL
        trust-store-location: ${javax.net.ssl.trustStore}
        trust-store-password: ${javax.net.ssl.trustStorePassword}
      properties:
        #security.protocol: SASL_SSL
        sasl:
          mechanism: PLAIN
          jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username="${tiltak.tilsagnsbrev.serviceuser}" password="${tiltak.tilsagnsbrev.serviceuser.password}";
#        ssl.truststore:
#          location: ${javax.net.ssl.trustStore}
#          password: ${javax.net.ssl.trustStorePassword}


  main:
    banner-mode: "console"

tilsagnsbrev:
  joark:
    uri: http://localhost:8090
  sts:
    uri: http://localhost:8090
    bruker: ${SRVBRUKER}
    passord: ${SRVPASSORD}

