spring:
  kafka:
    bootstrap-servers: b27apvl00045.preprod.local:8443, b27apvl00046.preprod.local:8443, b27apvl00047.preprod.local:8443
    client-id: tiltak-tilsagnsbrev
    properties:
      security.protocol: SASL_SSL
      sasl:
        mechanism: PLAIN
        jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username="${tilsagnsbrev_srvuser}" password="${tilsagnsbrev_srvpwd}";
      ssl.truststore:
        location: ${javax.net.ssl.trustStore}
        password: ${javax.net.ssl.trustStorePassword}

tilsagnsbrev:
  database:
    database-navn: tiltak-tilsagnsbrev-feilet-preprod
    database-url: ${spring.datasource.url}
    vault-sti: postgresql/preprod-fss/creds
    minimum-idle: 1
    maximum-pool-size: 2
    max-lifetime: 300000
  integrasjon:
    pdfgen:
      uri: ${tilsagnsbrev.pdfgen.url}
    joark:
      uri: ${tilsagnsbrev.joark.url}
    sts:
      uri: ${tilsagnsbrev.sts.url}
      ws-uri: ${tilsagnsbrev.sts.ws.url}
      bruker: ${tilsagnsbrev_srvuser}
      passord: ${tilsagnsbrev_srvpwd}
    altinn:
      uri: ${altinn.correspondence.url}
      systemBruker: ${tilsagnsbrev_altinn_system_bruker}
      systemPassord: ${tilsagnsbrev_altinn_system_passord}