server.servlet.context-path: /tiltak-tilsagnsbrev

spring:
  kafka:
#    bootstrap-servers: d26apvl00159.test.local:8443,d26apvl00160.test.local:8443,d26apvl00161.test.local:8443
    bootstrap-servers: b27apvl00045.preprod.local:8443, b27apvl00046.preprod.local:8443, b27apvl00047.preprod.local:8443
    client-id: tiltak-tilsagnsbrev
    properties:
      security.protocol: SASL_SSL
      sasl:
        mechanism: PLAIN
        jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username="${tilsagnsbrev_srvuser}" password="${tilsagnsbrev_srvpwd}";
      ssl.truststore:
        location: ${javax.net.ssl.trustStore}
        password: ${javax.net.ssl.trustStorePassword}

tilsagnsbrev:
  integrasjon:
    pdfgen:
      uri: uri
    altinn:
      queue: QA.Q1_EMOTTAK.ALTUT_INN
    joark:
      uri: uri
    sts:
      uri: uri
      bruker: ${tilsagnsbrev_srvuser}
      passord: ${tilsagnsbrev_srvpwd}

ibm:
  mq:
    queueManager: MQ1LSC02
    channel: Q1_TILTAK_TILSAGNSBR
    connName: b27apvl176.preprod.local(1412)
    user: ${tilsagnsbrev_srvuser}
    password: ${tilsagnsbrev_srvpwd}