spring:
  datasource:
    platform: postgres
    driverClassName: org.postgresql.Driver
  kafka:
    bootstrap-servers: fyllinn
    client-id: tiltak-tilsagnsbrev
    properties:
      security.protocol: SASL_SSL
      sasl:
        mechanism: PLAIN
        jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username="${tilsagnsbrev_srvuser}" password="${tilsagnsbrev_srvpwd}";
      ssl.truststore:
        location: ${javax.net.ssl.trustStore}
        password: ${javax.net.ssl.trustStorePassword}

tilsagnsbrev:
  database:
    database-navn: tiltak-tilsagnssbrev-feilet
    database-url: ${spring.datasource.url}
    vault-sti: postgresql/prod-fss
    minimum-idle: 1
    maximum-pool-size: 2
    max-lifetime: 300000
  integrasjon:
    pdfgen:
      uri: uri
    joark:
      uri: uri
    sts:
      uri: uri
      ws-uri: uri
      bruker: ${tilsagnsbrev_srvuser}
      passord: ${tilsagnsbrev_srvpwd}
    altinn:
      uri: ${altinn.correspondence.url}
      systemBruker: ${tilsagnsbrev_altinn_system_bruker}
      systemPassord: ${tilsagnsbrev_altinn_system_passord}