logging:
  level:
    no.nav.tag.tilsagnsbrev: INFO
    org.springframework.kafka.listener.LoggingErrorHandler: OFF
    org.apache.cxf.services.*: WARN
    org.apache.cxf.ws.*: ERROR

spring:
  datasource:
    url: 'jdbc:postgresql://A01DBVL035.adeo.no:5432/tiltak-tilsagnsbrev-p15-prod'
  kafka:
    bootstrap-servers: ${KAFKA_BROKERS}
    client-id: tiltak-tilsagnsbrev
    properties:
      security.protocol: SSL
      ssl:
        keystore:
          type: PKCS12
          location: ${KAFKA_KEYSTORE_PATH}
          password: ${KAFKA_CREDSTORE_PASSWORD}
        truststore:
          location: ${KAFKA_TRUSTSTORE_PATH}
          password: ${KAFKA_CREDSTORE_PASSWORD}
    consumer:
      group-id: ${tilsagnsbrev.consumer.group.id}

tilsagnsbrev:
  retry:
    cron: ${tilsagnsbrev.process.cron}
  database:
    database-navn: tiltak-tilsagnsbrev-p15-prod
    database-url: ${spring.datasource.url}
    vault-sti: postgresql/prod-fss
    minimum-idle: 1
    maximum-pool-size: 1
    max-lifetime: 300000
  integrasjon:
    joark:
      uri: ${tilsagnsbrev.joark.url}
    sts:
      uri: ${tilsagnsbrev.sts.url}
      ws-uri: ${tilsagnsbrev.sts.ws.url}
      bruker: ${tilsagnsbrev_srvuser}
      passord: ${tilsagnsbrev_srvpwd}
    altinn:
      uri: ${altinn.correspondence.url}
      systemBruker: ${tilsagnsbrev_altinn_system_bruker}
      systemPassord: ${tilsagnsbrev_altinn_system_passord}