server.servlet.context-path: /tiltak-tilsagnsbrev

spring:
  kafka:
    consumer:
      bootstrap-servers: ${spring.embedded.kafka.brokers}

  main:
    banner-mode: "console"

tilsagnsbrev:
  integrasjon:
    pdfurl: http://localhost:5913


ibm-mq:
  queueManager: QM1
  channel: DEV.ADMIN.SVRCONN
  connName: localhost(32794)
  user: admin
  password: passw0rd