server:
  port: 8082

spring:
  kafka:
    consumer:
      bootstrap-servers: ${spring.embedded.kafka.brokers}

  main:
    banner-mode: "console"

tilsagnsbrev:
  integrasjon:
    pdfgen:
      uri: http://localhost:5913
    altinn:
      queue: DEV.QUEUE.1
    joark:
      uri: uri
    sts:
      uri: uri
      bruker: bruker
      passord: passord

ibm:
  mq:
    queueManager: QM1
    channel: DEV.ADMIN.SVRCONN
    connName: localhost(32794)
    user: admin
    password: passw0rd