server:
  port: 8082

spring:
  kafka:
    consumer:
      bootstrap-servers: ${spring.embedded.kafka.brokers}

  main:
    banner-mode: "console"

tilsagnsbrev:
  integrasjon:
    pdfgen:
      uri: http://localhost:5913
    joark:
      uri: uri
    sts:
      uri: uri
      ws-uri: http://localhost:8090
      bruker: ${tilsagnsbrev_srvuser}
      passord: ${tilsagnsbrev_srvpwd}
    altinn:
      uri: http://localhost:8088
      user: bruker
      password: passord