server:
  port: 8082

spring:
  kafka:
    consumer:
      bootstrap-servers: ${spring.embedded.kafka.brokers}

  main:
    banner-mode: "console"

tilsagnsbrev:
  integrasjon:
    pdfgen:
      uri: http://localhost:5913
    joark:
      uri: uri
    sts:
      uri: uri
      bruker: bruker
      passord: passord
    altinn:
      queue: DEV.QUEUE.1
      queueManager: QM1
      channel: DEV.ADMIN.SVRCONN
      user: ${MQ_USER}
      password: ${MQ_PWD}
      host: localhost
      port: 32794