logging:
  level:
    no.nav.tag.tilsagnsbrev: INFO

spring:
  kafka:
    bootstrap-servers: ${KAFKA_BROKERS}
    client-id: tiltak-tilsagnsbrev
    properties:
      security.protocol: SSL
      ssl:
        keystore:
          type: PKCS12
          location: ${KAFKA_KEYSTORE_PATH}
          password: ${KAFKA_CREDSTORE_PASSWORD}
        truststore:
          location: ${KAFKA_TRUSTSTORE_PATH}
          password: ${KAFKA_CREDSTORE_PASSWORD}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: ${tilsagnsbrev.consumer.group.id}
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

tilsagnsbrev:
  retry:
    cron: ${tilsagnsbrev.process.cron}
  database:
    database-navn: tiltak-tilsagnsbrev-preprod
    database-url: ${spring.datasource.url}
    vault-sti: postgresql/preprod-fss
    minimum-idle: 1
    maximum-pool-size: 1
    max-lifetime: 300000
  integrasjon:
    joark:
      uri: ${tilsagnsbrev.joark.url}
    sts:
      uri: ${tilsagnsbrev.sts.url}
      ws-uri: ${tilsagnsbrev.sts.ws.url}
      bruker: ${tilsagnsbrev_srvuser}
      passord: ${tilsagnsbrev_srvpwd}
    altinn:
      uri: ${altinn.correspondence.url}
      systemBruker: ${tilsagnsbrev_altinn_system_bruker}
      systemPassord: ${tilsagnsbrev_altinn_system_passord}