spring:
  main:
    banner-mode: "off"

  kafka:
    bootstrap-servers: b27apvl00045.preprod.local:8443,b27apvl00046.preprod.local:8443, b27apvl00047.preprod.local:8443
    client-id: tiltak-tilsagnsbrev
    properties:
      security.protocol: SASL_SSL
      sasl:
        mechanism: PLAIN
        jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username="${tilsagnsbrev_srvuser}" password="${tilsagnsbrev_srvpwd}";
      ssl.truststore:
        location: ${javax.net.ssl.trustStore}
        password: ${javax.net.ssl.trustStorePassword}


tilsagnsbrev:
  integrasjon:
    pdfurl: url