version: 2
orbs:
  nais: navikt/nais-deployment@dev:master
  env: christeredvartsen/persist-env@0.0.4

executors:
  deployment-cli:
    docker:
      - image: navikt/deployment-cli:latest
    environment:
      TEAM: teamtag
      REGISTRY: docker.io

jobs:
  build:
    docker:
      - image: circleci/openjdk:11
    working_directory: ~/repo
    steps:
      - checkout
      - env/set-env-var:
          var-name: RELEASE_VERSION
          var-value: $(git log -1 --pretty='%ad' --date=format:'%Y%m%d%H%M')_$(git log -n 1 --pretty=format:'%h')
      - env/set-env-var:
          var-name: IMAGE_NAME
          var-value: $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME
      - env/persist-env
      - restore_cache:
          keys:
            - maven-repo-v1-{{ .Branch }}-{{ checksum "pom.xml" }}
            - maven-repo-v1-{{ .Branch }}-
            - maven-repo-v1-
      - run:
          name: Bygger med Maven
          command: mvn clean package -P-kopier-dependencies
      - save_cache:
          paths:
            - ~/.m2
          key: maven-repo-v1-{{ .Branch }}-{{ checksum "pom.xml" }}
      - persist_to_workspace:
          root: .
          paths:
            - target/*.jar

  docker-build:
    docker:
      - image: "navikt/deployment-cli:v0.1.5"
    working_directory: ~/repo
    steps:
      - checkout
      - env/attach-env
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Move target folder to correct location
          command: cp -r /tmp/workspace/target ~/repo/target
      - nais/docker:
          registry: $REGISTRY
          image: $IMAGE_NAME
          tag: $RELEASE_VERSION

  deploy-til-dev:
    docker:
      - image: "navikt/deployment-cli:v0.1.5"
    steps:
      - checkout
      - deploy:
          miljo: "dev-fss"

  deploy-til-prod:
    docker:
      - image: "navikt/deployment-cli:v0.1.5"
    steps:
      - checkout
      - deploy:
          miljo: "prod-fss"

commands:
  deploy:
    description: 'Deploy til et gitt miljø'
    parameters:
      miljo:
        type: string
    steps:
      - checkout
      - env/attach-env
      - run:
          name: Unpack Private Key
          command: echo $GITHUB_PRIVATE_KEY | base64 -d > .circleci/github.key.pem
      - nais/deploy-with-gh-app:
          repo: $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME
          nais-template: naiserator.yaml
          team: $TEAM
          github-app-id: 43789
          image: $REGISTRY/$IMAGE_NAME
          tag: $RELEASE_VERSION
          environment: << parameters.miljo >>
          template-vars: nais/<< parameters.miljo >>.json
          enable-vars: true


workflows:
  version: 2
  default:
    jobs:
      - build:
          context: tag-ci
      - docker-build:
          context: NAIS deployment
          requires:
            - build

      - godkjenn-deploy-til-dev:
          type: approval
          requires:
            - docker-build
          filters:
            branches:
              ignore:
                - master

      - deploy-til-dev:
          context: tag-ci
          requires:
            - godkjenn-deploy-til-dev

      - godkjenn-deploy-til-prod:
          type: approval
          requires:
            - build
          filters:
            branches:
              only:
                - master

      - deploy-til-prod:
          context: tag-ci
          requires:
            - godkjenn-deploy-til-prod
          filters:
            branches:
              only: master