apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: tiltak-tilsagnsbrev
  namespace: arbeidsgiver
  labels:
    team: team-tiltak
spec:
  groups:
    - name: tiltak-tilsagnsbrev-alert
      rules:
        - alert: applikasjon nede
          expr: sum(up{app="tiltak-tilsagnsbrev", job="nais-system/monitoring-apps-tenant"}) == 0
          for: 1s
          annotations:
            summary: tiltak-tilsagnsbrev er nede
            action: "`kubectl describe pod {{ $labels.kubernetes_pod_name }} -n {{ $labels.kubernetes_namespace }}` for events, og `kubectl logs {{ $labels.kubernetes_pod_name }} -n {{ $labels.kubernetes_namespace }}` for logger"
          labels:
            namespace: team-tiltak
            severity: critical

        - alert: høy feilrate i logger
          expr: (sum by (log_app, log_namespace) (rate(logd_messages_total{log_app="tiltak-tilsagnsbrev",log_level=~"Error"}[3m]))) > 3
          for: 1s
          annotations:
            summary: tiltak-tilsagnsbrev feiler mye
            action: "`kubectl describe pod {{ $labels.kubernetes_pod_name }} -n {{ $labels.kubernetes_namespace }}` for events, og `kubectl logs {{ $labels.kubernetes_pod_name }} -n {{ $labels.kubernetes_namespace }}` for logger"
          labels:
            namespace: team-tiltak
            severity: critical

        - alert: tilsagnsbrev feilet!
          expr: sum(increase(retry_fail_total{app="tiltak-tilsagnsbrev"} [5m])) > 0
          for: 1m
          annotations:
            summary: |-
              Tilsagnsbrev feilet v/behandling :this-is-fine-fire: Sjekk loggene om noe bør gjøres!
            action: "Sjekk logs.adeo.no for logger: https://logs.adeo.no/app/r/s/HT3Nd"
          labels:
            namespace: team-tiltak
            severity: critical