name: Bygg og deploy master

on:
  push:
    branches:
      - 'master'

jobs:
  build:
    name: Bygg
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    timeout-minutes: 5
    outputs:
      image: ${{ steps.docker-build-push.outputs.image }}
    steps:
      - name: Lukk deployment-issues
        uses: actions/github-script@0.5.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.issues.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open',
              labels: ['deploy']
            }).then(response => {
              response.data.forEach(issue => {
                github.issues.update({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: issue.number,
                  state: 'closed'
                });
              });
            });

      - name: Sjekk ut kode
        uses: actions/checkout@v4

      - name: Oppsett Java 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin
          cache: maven

      - name: Bygg og test med Maven
        run: mvn package -B -Dsurefire.useFile=false

      - name: Push docker image to GAR
        uses: nais/docker-build-push@v0
        id: docker-build-push
        with:
          team: arbeidsgiver
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}

  deploy-dev:
    name: Deploy til dev
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Sjekk ut kode
        uses: actions/checkout@v4
      - uses: nais/deploy/actions/deploy@v2
        name: Deploy til dev-fss
        env:
          CLUSTER: dev-fss
          RESOURCE: nais/nais.yaml,nais/alerterator.yaml
          VARS: nais/dev-fss.json
          VAR: image=${{ needs.build.outputs.image }}

  deploy-prod:
    name: Deploy til prod
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Sjekk ut kode
        uses: actions/checkout@v4
      - uses: nais/deploy/actions/deploy@v2
        name: Deploy til prod-fss
        env:
          CLUSTER: prod-fss
          RESOURCE: nais/nais.yaml,nais/alerterator.yaml
          VARS: nais/prod-fss.json
          VAR: image=${{ needs.build.outputs.image }}
