name: Deploy til dev
on:
  repository_dispatch:
    types: [deploy-command]

env:
  GITHUB_REPOSITORY: ${{ github.repository }}
 
jobs:
  deploy-branch:
    name: Deploy til dev
    runs-on: ubuntu-latest
    
    steps:
      - name: Finn REPOSITORY_NAME
        run: echo "REPOSITORY_NAME=$(echo "$GITHUB_REPOSITORY" | awk -F / '{print $2}" >> $GITHUB_ENV

      - name: Sett IMAGE_BASE
        run: echo "IMAGE_BASE=$(echo "docker.pkg.github.com/$GITHUB_REPOSITORY/$REPOSITORY_NAME")" >> $GITHUB_ENV

      - name: Kommenterer med link til action
        uses: actions/github-script@0.5.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.issues.createComment({
              issue_number: ${{ github.event.client_payload.github.payload.issue.number }},
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Deploy satt i gang: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}'
            })

      - name: Sjekk ut kode
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.client_payload.slash_command.arg1 }}
          fetch-depth: 0

      - name: Sett miljøvariabel COMMIT
        run: echo "COMMIT=$(git rev-parse HEAD)" >> $GITHUB_ENV

      - name: Sjekk om COMMIT er oppdatert mot master
        run: |
          git fetch origin master
          git merge-base --is-ancestor origin/master $COMMIT

      - name: Sett miljøvariabel IMAGE
        run: echo "IMAGE=$IMAGE_BASE:$COMMIT" >> $GITHUB_ENV

      - name: Deploy til dev-fss
        uses: nais/deploy/actions/deploy@v1
        env:
          TEAM: arbeidsgiver
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-fss
          RESOURCE: nais/naiserator.yaml
          PRINT_PAYLOAD: true
          VARS: nais/dev-fss.json
          REF: ${{ env.COMMIT }}
          IMAGE: ${{ env.IMAGE }}
          
      - name: Oppdater kommentar med deployment status ved feil
        if: failure()
        uses: actions/github-script@0.5.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.issues.createComment({
              issue_number: ${{ github.event.client_payload.github.payload.issue.number }},
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Deploy av <b>${{ env.COMMIT }}</b> feilet ❌'
            })

      - name: Oppdater kommentar med deployment status ved ok
        if: success()
        uses: actions/github-script@0.5.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.issues.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['deploy', 'dev-fss']
            }).then(response => {
              response.data.forEach(issue => {
                github.issues.removeLabel({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: issue.number,
                  name: 'dev-fss'
                });
              });
            });

            github.issues.createComment({
              owner: context.issue.owner,
              repo: context.issue.repo,
              issue_number: ${{ github.event.client_payload.github.payload.issue.number }},
              body: 'Deploy av <b>${{ env.COMMIT }}</b> ok ✅'
            });

            github.issues.addLabels({
              owner: context.issue.owner,
              repo: context.issue.repo,
              issue_number: ${{ github.event.client_payload.github.payload.issue.number }},
              labels: ['dev-fss']
            });
